### PR TITLE
Docusaurus website for community repo

### PR DESCRIPTION
**Pull request by maoo**
@finos/finos-staff - This is the website preview - https://blissful-lovelace-7f2b3a.netlify.app/

@TheJuanAndOnly99 is working on some UI improvements for the homepage, which will be ready in the next day or 2.

We expect to merge this PR by Friday, but the launch of the website can be scheduled for later. This will allow us to incrementally update and review the website content (and look 'n feel), and announce the website when we feel it's ready. We will also create the DNS entry for `community.finos.org`.

Note that we have updated links in the main `README.md`, so that users can still browse content via http://github.com/finos/community .

### CODE REVIEW

**Comment by mcleo-d** [comment]
## Description
Subscribe email link not rendering as a clickable link

## Link 
https://blissful-lovelace-7f2b3a.netlify.app/docs/journey/engage#mailing-lists

## Screenshot
Screenshot 2022-03-16 at 11 36 04

**Comment by mcleo-d** [comment]
## Description 
EasyCLA links to a 404 error (which could be fixed when PR merged?)
Screenshot 2022-03-16 at 11 41 19

## Link
https://blissful-lovelace-7f2b3a.netlify.app/docs/journey/participate

## Screenshot
Screenshot 2022-03-16 at 11 39 51

**Comment by mcleo-d** [comment]
## Description
References to PMC in Docusaurus content. This might be worth raising as a separate issue to edit?

## Link
https://blissful-lovelace-7f2b3a.netlify.app/docs/governance/Software-Projects/code-transfer#source-code-snapshot

## Screenshot
Screenshot 2022-03-16 at 11 49 23

**Comment by mcleo-d** [comment]
## Description
Is this content referring to a current development scenario?

## Link
https://blissful-lovelace-7f2b3a.netlify.app/docs/platforms/symphony-dev-pod

## Screenshot
Screenshot 2022-03-16 at 11 56 59

**Comment by mcleo-d** [comment]
## ODP 301 Redirects
Within this PR there is content that has been migrated from https://odp.finos.org. 

Do 301 redirects, or a deprecation plan, need to be put in place for current inbound links to viable ODP content. For example, FINOS Maintainers Cheatsheet and FINOS Slack references?

**Review by mcleo-d — CHANGES_REQUESTED** [review]

**Comment by maoo** [comment]
> ## Description
> Subscribe email link not rendering as a clickable link
> 
> ## Link
> https://blissful-lovelace-7f2b3a.netlify.app/docs/journey/engage#mailing-lists
> 
> ## Screenshot
> Screenshot 2022-03-16 at 11 36 04

Hi James! This is expected, since the email address is not a real one, so it is not expected that people use it. Agreed?

**Comment by maoo** [comment]
> ## ODP 301 Redirects
> Within this PR there is content that has been migrated from https://odp.finos.org.
> 
> Do 301 redirects, or a deprecation plan, need to be put in place for current inbound links to viable ODP content. For example, FINOS Maintainers Cheatsheet and FINOS Slack references?

Yes, it is already part of https://github.com/finos/metadata/issues/1148 . Thanks for the reminder tho!

**Comment by maoo** [comment]
> ## Description
> Is this content referring to a current development scenario?
> 
> ## Link
> https://blissful-lovelace-7f2b3a.netlify.app/docs/platforms/symphony-dev-pod
> 
> ## Screenshot
> Screenshot 2022-03-16 at 11 56 59

yes, this is all true! 😄

**Comment by maoo** [comment]
Great feedback @mcleo-d , thank you! 

As we've integrated everything, I'll go ahead and merge this PR. Thanks so much for the great feedback! And TY @agitana !

**Pull request merged**
